version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin_my_blog
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: my_blog
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
